// Define the damage assessment types
export interface PecuniaryDamage {
  id: string;
  status: string;
  notes: string;
  evidence_needed_ref: string[];
}

export interface NonPecuniaryDamage {
  id: string;
  status: string;
  notes: string;
  evidence_needed_ref: string[];
}

// Define the complete AdverseAction interface with damage assessment fields
export interface AdverseAction {
  document_index: number;
  document_source: string;
  sender_name: string;
  sender_address: string | null;
  recipient_name: string;
  recipient_address: string | null;
  recipient_email?: string | null;
  date: string;
  application_date?: string;
  decision_date?: string;
  action_type: string;
  initiated_by?: string;
  details?: any;
  reasons: string[];
  credit_report_agency: string;
  credit_report_agency_details: string | null;
  credit_score: number | null;
  credit_score_date: string | null;
  credit_score_range: string | null;
  credit_score_factors: string[] | null;
  comparison?: string;
  applicable_pecuniary_damages?: PecuniaryDamage[];
  applicable_non_pecuniary_damages?: NonPecuniaryDamage[];
}

// Helper function to ensure all required fields are present
function createAdverseAction(data: Partial<AdverseAction>): AdverseAction {
  return {
    document_index: data.document_index!,
    document_source: data.document_source!,
    sender_name: data.sender_name!,
    sender_address: data.sender_address || null,
    recipient_name: data.recipient_name!,
    recipient_address: data.recipient_address || null,
    recipient_email: data.recipient_email || null,
    date: data.date!,
    application_date: data.application_date,
    decision_date: data.decision_date,
    action_type: data.action_type!,
    initiated_by: data.initiated_by,
    details: data.details,
    reasons: data.reasons || [],
    credit_report_agency: data.credit_report_agency!,
    credit_report_agency_details: data.credit_report_agency_details || null,
    credit_score: data.credit_score || null,
    credit_score_date: data.credit_score_date || null,
    credit_score_range: data.credit_score_range || null,
    credit_score_factors: data.credit_score_factors || null,
    comparison: data.comparison,
    applicable_pecuniary_damages: data.applicable_pecuniary_damages,
    applicable_non_pecuniary_damages: data.applicable_non_pecuniary_damages,
  };
}

// Adverse action data with framework links and damage assessment information
export const adverseActionsData: AdverseAction[] = [
  createAdverseAction({
    document_index: 1,
    document_source: 'Bank of America (Letter - Credit Limit Change)',
    sender_name: 'Bank of America',
    sender_address: 'PO Box 660441, Dallas, TX 75266-0441',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 CHURCH RD, EASTON PA 18045-2971',
    date: '2024-03-07',
    action_type: 'Credit Limit Reduction',
    details: {
      account_ending_in: '1775',
      new_total_credit_line: '2000.00',
    },
    reasons: [
      'Utilization too high',
      'Number of revolving accounts with balances',
      'Current or past delinquency/derog/collection',
      'Balance too high relative to limit',
    ],
    credit_report_agency: 'TransUnion',
    credit_report_agency_details: 'PO Box 1000, Chester, PA 19016-1000, 1-800-888-4213',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction and reasons.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 2,
    document_source: 'Huebner Chevrolet Subaru (Letter - Financing Denial)',
    sender_name: 'Huebner Chevrolet Subaru',
    sender_address: '1155 CANTON ROAD, CARROLLTON, OH 44615',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr Apt 456-2, Los Angeles, CA 90045',
    date: '2024-02-13',
    action_type: 'Vehicle Financing Application Denial',
    details: 'Dealer could not secure acceptable terms.',
    reasons: ['Inability to find finance company'],
    credit_report_agency: 'Dealer Obtained (CRA unspecified)',
    credit_report_agency_details: 'Equifax, Experian, TransUnion listed as possibilities',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial, vehicle need.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 3,
    document_source: 'Chase (Letter - Credit Limit Adjustment)',
    sender_name: 'Chase Card Services',
    sender_address: 'PO Box 15298, Wilmington, DE 19850-5298',
    recipient_name: 'Nyree D Hinton',
    recipient_address: '4254 Church Road, Easton PA 18045',
    date: '2024-01-18',
    action_type: 'Credit Limit Reduction',
    details: {
      account_ending_in: '0757',
      new_credit_line: '4600.00',
    },
    reasons: [
      'Major derogatory items',
      'Delinquent obligations',
      'High usage',
      'Low payments history',
    ],
    credit_report_agency: 'Experian (TRW)',
    credit_report_agency_details: 'P.O. Box 2002, Allen, TX 75013, (888) 397-3742',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction and derogatory reasons.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 4,
    document_source: 'Chase (Letter - Credit Limit Adjustment - Amazon Card)',
    sender_name: 'Chase Card Services',
    sender_address: 'PO Box 15298, Wilmington, DE 19850-5298',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456, Los Angeles PA 90045',
    date: '2024-01-18',
    action_type: 'Credit Limit Reduction',
    details: {
      account_ending_in: '7293',
      new_credit_line: '4600.00',
    },
    reasons: [
      'Major derogatory items',
      'Delinquent obligations',
      'High usage',
      'Low payments history',
    ],
    credit_report_agency: 'Experian (TRW)',
    credit_report_agency_details: 'P.O. Box 2002, Allen, TX 75013, (888) 397-3742',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction and derogatory reasons.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 5,
    document_source: 'Ally Bank (Letter - Auto Financing Denial)',
    sender_name: 'Ally Bank',
    sender_address: 'PO BOX 1048, HARTFORD CT 06143',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 CENTER DR APT 456-2, LOS ANGELES, CA 90045',
    date: '2024-03-12',
    action_type: 'Auto Financing Application Denial',
    initiated_by: 'Carmax Auto Superstores California, Llc',
    details: {
      application_number: '1142194213',
    },
    reasons: ['Decision based on credit report(s)'],
    credit_report_agency: 'Experian; SageStream, LLC',
    credit_report_agency_details:
      'Experian: PO Box 2002 Allen TX 75013 888-397-3742; SageStream: PO Box 105108 Atlanta GA 30348-5108 888-395-0277',
    credit_score: null,
    credit_score_date: '2024-02-26',
    credit_score_range: null,
    credit_score_factors: ['Insufficient information about credit history to calculate a score'],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carmax purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 6,
    document_source: 'Ally Bank (Letter - Auto Financing Denial)',
    sender_name: 'Ally Bank',
    sender_address: 'PO BOX 1048, HARTFORD CT 06143',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 CHURCH RD, EASTON, PA 18045',
    date: '2024-04-09',
    action_type: 'Auto Financing Application Denial',
    initiated_by: 'St. Charles Motor Cars, Llc (2020 JAGUAR F-TYPE)',
    details: {
      application_number: '1143445713',
    },
    reasons: ['Decision based on credit report(s) and score'],
    credit_report_agency: 'TransUnion; Experian; SageStream, LLC',
    credit_report_agency_details:
      'TransUnion: P.O. Box 1000 Chester PA 19022 800-888-4213; Experian: PO Box 40 Allen TX 75013-0043 844-922-2743; SageStream: PO Box 105108 Atlanta GA 30348-5108 888-395-0277',
    credit_score: 686,
    credit_score_date: '2024-03-26',
    credit_score_range: '250-900',
    credit_score_factors: [
      'Proportion of balances to credit limits on bank revolving or other rev accts too high',
      'Proportion of loan balances to loan amounts is too high',
      'Length of time accounts have been established',
      'Amount owed on revolving accounts is too high',
      'Too many inquiries last 12 months',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if St. Charles purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 7,
    document_source: 'Ally Bank (Letter - Auto Financing Denial/Modified Offer)',
    sender_name: 'Ally Bank',
    sender_address: 'PO BOX 1048, HARTFORD CT 06143',
    recipient_name: 'Nyree Hinton',
    recipient_address: '616 MASSELIN AV, Apt 2, LOS ANGELES, CA 90036',
    date: '2024-10-07',
    action_type: 'Auto Financing Application Denial (as submitted); Modified terms offered',
    initiated_by: 'Carbeeco (2021 JAGUAR FTYPE)',
    details: {
      application_number: '1149866599',
      credit_scores: {
        experian_box_2002: 681,
        experian_box_40: 679,
      },
    },
    reasons: ['Decision based on credit report(s) and score'],
    credit_report_agency:
      'Experian (PO Box 2002); TransUnion; Experian (PO Box 40); SageStream, LLC',
    credit_report_agency_details: 'Multiple agencies with different addresses',
    credit_score: 681,
    credit_score_date: '2024-09-16',
    credit_score_range: '250-900 (Experian Box 2002); 300-850 (Experian Box 40)',
    credit_score_factors: [
      'Ratio of balance to limit on bank revolving or other rev accts too high',
      'Proportion of loan balances to loan amounts is too high',
      'Length of time accounts have been established',
      'Amount owed on revolving accounts is too high',
      'Too many inquiries last 12 months',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: "Quantify IF modified terms accepted AND worse than 'but-for'.",
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carbeeco purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial/modified offer.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 8,
    document_source: 'Chase Auto (Letter - Auto Loan Denial)',
    sender_name: 'Chase Auto (JPMorgan Chase Bank, N.A.)',
    sender_address: '1111 Polaris Parkway, Columbus, Ohio 43240',
    recipient_name: 'Nyree D Hinton',
    recipient_address: '4254 CHURCH RD, EASTON PA 18045',
    date: '2024-02-11',
    action_type: 'Vehicle Credit Application Denial',
    initiated_by: 'Self/Unknown Dealer (20 JAGUAR F-TYPE)',
    details: null,
    reasons: ['FORECLOSURE, REPOSSESSION, COLLECTION AND/OR CHARGE-OFF'],
    credit_report_agency: 'Implied',
    credit_report_agency_details: null,
    credit_score: 542,
    credit_score_date: '2024-01-31',
    credit_score_range: '250-900',
    credit_score_factors: [
      'Serious delinquency',
      'Time since delinquency is too recent or unknown',
      'Ratio of balances to limits on bankcards or revolving accounts too high',
      'Length of time accounts have been established',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Jaguar purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial & severe reasons cited.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Severe reasons damage reputation.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 9,
    document_source: 'Chase Auto (Email - Auto Loan Denial Notification)',
    sender_name: 'Chase',
    sender_address: null,
    recipient_name: 'Nyree',
    recipient_email: 'NYREEHINTON@GMAIL.COM',
    date: '2024-02-08',
    action_type: 'Auto Financing Application Denial Notification',
    details: 'Refers to decision made 2024-01-31 (Doc 8). States letter will follow.',
    reasons: ['Unable to approve'],
    credit_report_agency: 'Not Specified',
    credit_report_agency_details: null,
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs associated with receiving/handling notification.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Contributes to overall stress/frustration.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to pattern of denials.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 10,
    document_source: 'Essex Property Trust (Implied) (Letter - Rental Application Decision)',
    sender_name: 'Essex Property Trust (Implied)',
    sender_address: null,
    recipient_name: 'Nyree Hinton',
    recipient_address: 'Related to 616 Masselin Avenue, 210 application',
    date: '2024-06-04',
    action_type: 'Conditional Rental Application Approval',
    details: {
      property: 'Tiffany Court',
      condition: 'Requires additional security deposit of $2,187',
    },
    reasons: [
      'High balances',
      'Too many inquiries',
      'High revolving balances',
      'Recent auto delinquency too short',
    ],
    credit_report_agency:
      'TransUnion Consumer Solutions; TransUnion Rental Screening Solutions; etc.',
    credit_report_agency_details:
      'TransUnion Consumer Solutions: PO Box 2000 Chester, PA 19022-2000 1-800-916-8800',
    credit_score: 605,
    credit_score_date: '2024-06-05',
    credit_score_range: '350-850',
    credit_score_factors: [
      'High balances',
      'Too many inquiries',
      'High revolving balances',
      'Recent auto delinquency too short',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-PAY',
        status: 'Applicable - $2,187 Amount Stated',
        notes: 'Direct cost imposed by adverse action.',
        evidence_needed_ref: ['PEC-PAY-01 (Proof of Payment)'],
      },
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable rental application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute reasons.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration/humiliation of needing higher deposit.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 11,
    document_source: 'Unknown Credit Monitoring Service (Image - Score Update)',
    sender_name: 'Unknown',
    sender_address: null,
    recipient_name: 'Nyree Hinton',
    recipient_address: null,
    date: '2024-01-19',
    action_type: 'Credit Score Update / Change Alert',
    details: 'Score dropped 75 points since 2023-10-05.',
    credit_report_agency: 'TransUnion',
    credit_report_agency_details: null,
    credit_score: 583,
    credit_score_date: '2024-01-19',
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify monitoring cost IF service purchased *because* of discovered issues.',
        evidence_needed_ref: ['PEC-OOP-02'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Significant score drop is inherently stressful.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Directly documents damage to creditworthiness metric.',
        evidence_needed_ref: ['NONPEC-REP-03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 12,
    document_source: 'Capital One Auto Finance (Letter - Auto Financing Denial)',
    sender_name: 'Capital One Auto Finance',
    sender_address: '7933 Preston Road, Plano, TX 75024',
    recipient_name: 'Nyree Hinton',
    recipient_address: '616 MASSELIN AVE APT 210, LOS ANGELES CA 90036',
    date: '2024-09-24',
    application_date: '2024-09-16',
    action_type: 'Auto Financing Application Denial',
    initiated_by: 'VOLVO PALO ALTO',
    details: {
      reference: '280125460',
    },
    reasons: ['Too many delinquent past or present Capital One installment credit obligation(s)'],
    credit_report_agency: 'None Pulled (Internal History)',
    credit_report_agency_details: 'Decision based on internal Capital One history.',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee paid to Volvo PA.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Volvo purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes:
          'Stress/frustration from denial based on internal history potentially linked to original dispute.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 13,
    document_source: 'Capital One Auto Finance (Letter - Auto Financing Denial)',
    sender_name: 'Capital One Auto Finance',
    sender_address: '7933 Preston Road, Plano, TX 75024',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 CENTER DR APT 456-2, LOS ANGELES CA 90045',
    date: '2024-03-06',
    action_type: 'Auto Financing Request Denial',
    details: {
      reference: '266820386',
    },
    reasons: ['Too many delinquent past or present Capital One installment credit obligation(s)'],
    credit_report_agency: 'Not Mentioned (Assumed Internal)',
    credit_report_agency_details: null,
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes:
          'Stress/frustration from denial based on internal history potentially linked to original dispute.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 14,
    document_source: 'Bank of America (Letter - Credit Limit Change)',
    sender_name: 'Bank of America',
    sender_address: 'PO Box 660441, Dallas, TX 75266-0441',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 CHURCH RD, EASTON PA 18045-2971',
    date: '2024-01-03',
    action_type: 'Credit Limit Reduction',
    details: {
      account_ending_in: '4041',
      new_total_credit_line: '1900.00',
    },
    reasons: [
      'Limited/no deposit/investment balances',
      'Number revolving accounts w balances',
      'Current/past delinquency/derog/collection',
      'Current/past delinquency w us',
    ],
    credit_report_agency: 'TransUnion',
    credit_report_agency_details: 'PO Box 1000, Chester, PA 19016-1000, 1.800.888.4213',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction and delinquency reasons.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 15,
    document_source: 'PA Forward Student Loans (Email - Loan Decision)',
    sender_name: 'PA Forward Student Loans (by Pheaa)',
    sender_address: 'no_reply@apply.pheaa.org',
    recipient_name: 'Nyree',
    recipient_email: 'NYREEHINTON@GMAIL.COM',
    date: '2024-02-08',
    application_date: '2024-01-19',
    action_type: 'Student Loan Application Denial (as single applicant)',
    details: {
      application_id: '6105954',
      condition: 'Offer to add qualified co-signer by 2024-03-04',
    },
    reasons: ['Credit Score does not meet minimum requirements'],
    credit_report_agency: 'Not Specified (Implied)',
    credit_report_agency_details: null,
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost funding obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Direct link to quantifying Harvard withdrawal impact.',
        evidence_needed_ref: ['PEC-OPP-01', 'PEC-OPP-02 (Harvard)'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial impacting education.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 16,
    document_source: 'Apple Card/Goldman Sachs (Email - Credit Limit Change)',
    sender_name: 'Apple Card Support / Goldman Sachs Bank USA',
    sender_address: undefined,
    recipient_name: 'Nyree Hinton',
    recipient_email: 'nyreehinton@gmail.com',
    date: '2024-01-16',
    action_type: 'Credit Limit Reduction',
    details: {
      new_credit_limit: '2200.00',
    },
    reasons: ['TransUnion report shows recently reported past due on one or more account(s).'],
    credit_report_agency: 'TransUnion Consumer Solutions',
    credit_report_agency_details: null,
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction based on past due reason.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 17,
    document_source: 'American Credit Acceptance (Letter - Auto Loan Denial/Modified Offer)',
    sender_name: 'American Credit Acceptance, LLC',
    sender_address: '961 E. Main St. 2nd Floor, Spartanburg, SC 29302',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456-2, Los Angeles, CA 90045',
    date: '2024-03-03',
    action_type: 'Auto Loan Application Denial (as submitted); Modified terms offered',
    initiated_by: 'CARMAX 7810-LAX',
    details: {
      application_number: 'XXXX6243',
      condition: 'Modified offer via dealer',
    },
    reasons: ['Not specified, requires contact'],
    credit_report_agency: 'TransUnion',
    credit_report_agency_details: '2 Baldwin Place, Chester, PA 19022 (800) 888-4213',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: "Quantify IF modified terms accepted AND worse than 'but-for'.",
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carmax purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial/modified offer.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 18,
    document_source: 'Citi (Letter - Credit Limit Lowered)',
    sender_name: 'Citi',
    sender_address: 'PO Box 6494, Sioux Falls, SD 57117-6494',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 CHURCH RD, EASTON PA 18045-2971',
    date: '2024-02-05',
    action_type: 'Credit Limit Reduction',
    details: {
      account: 'Citi® Double Cash Mastercard®',
      account_ending_in: '1752',
      new_credit_limit: '1510',
      cash_advance_limit: '0',
    },
    reasons: [
      'Score too low',
      'High revolving balances relative to limits',
      'Account(s) past due in last 12 months',
    ],
    credit_report_agency: 'Equifax Credit Information Services',
    credit_report_agency_details:
      'PO Box 740241, Atlanta, GA 30374-0241, 1-800-685-1111, www.equifax.com',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: [
      'Balances on revolving accounts too high relative to limits',
      'Account(s) past due in last 12 months',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction and past due reasons.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 19,
    document_source: 'Bank of Lake Mills / MPOWER Financing (Letter - Student Loan Denial)',
    sender_name: 'Bank of Lake Mills / MPOWER Financing',
    sender_address: '1101 Connecticut Ave NW Suite 900, Washington, DC 20036',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 Church Road, Easton, Pennsylvania, 18045',
    date: '2024-01-24',
    action_type: 'Fixed-rate student loan application denial',
    details: {
      loan_type: 'Fixed-rate student loan',
    },
    reasons: ['Delinquent past or present credit obligations'],
    credit_report_agency: 'TransUnion',
    credit_report_agency_details:
      'P.O.Box 1000, Chester, PA 19016, United States, Tel: 800-888-4213',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost funding obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Direct link to quantifying Harvard withdrawal impact.',
        evidence_needed_ref: ['PEC-OPP-01', 'PEC-OPP-02 (Harvard)'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial impacting education, reason cited.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 20,
    document_source: 'Bank of America (Notice - Credit Score Disclosure)',
    sender_name: 'Bank of America',
    sender_address: undefined,
    recipient_name: 'Nyree Hinton',
    recipient_address: undefined,
    date: undefined,
    action_type: 'Credit Score Disclosure',
    details: 'Associated with Doc 1 (Limit reduction 2024-03-07)',
    credit_report_agency: 'TransUnion',
    credit_report_agency_details:
      'PO Box 1000, Chester, PA 19016-1000, 800.888.4213, www.transunion.com/myoptions',
    credit_score: 628,
    credit_score_date: '2024-02-19',
    credit_score_range: '300-850 (FICO)',
    credit_score_factors: [
      'Serious delinquency',
      'High balance/limit ratio',
      'Time since delinquency recent/unknown',
      'Length of account history',
      'Too many inquiries',
    ],
    applicable_pecuniary_damages: [],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Documents low score and negative factors contributing to overall stress.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Documents negative factors harming reputation.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 21,
    document_source: 'Westlake Financial (Letter - Adverse Action Notice)',
    sender_name: 'Westlake Financial',
    sender_address: '4751 Wilshire Blvd, Suite 100, Los Angeles, CA 90010',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456-2, Los Angeles, CA 90045',
    date: '2024-03-03',
    action_type: 'Auto Loan Application Denial',
    initiated_by: 'CARMAX 7810-LAX',
    details: {
      application_number: 'XXXX6243',
      condition: 'Denial',
    },
    reasons: [
      'Delinquent credit obligations',
      'Excessive obligations in relation to income',
      'Length of employment',
    ],
    credit_report_agency: 'Experian',
    credit_report_agency_details: 'PO Box 2002, Allen, TX 75013, 888-397-3742, www.experian.com',
    credit_score: 628,
    credit_score_date: '2024-02-19',
    credit_score_range: '300-850 (FICO)',
    credit_score_factors: [
      'Serious delinquency',
      'High balance/limit ratio',
      'Time since delinquency recent/unknown',
      'Length of account history',
      'Too many inquiries',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carmax purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial and reasons cited.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 22,
    document_source: 'US Bank (Letter - Auto Loan Denial)',
    sender_name: 'U.S. Bank N.A.',
    sender_address: 'PO Box 1800, Saint Paul, MN 55101-0800',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456-2, Los Angeles, CA 90045',
    date: '2024-03-03',
    action_type: 'Auto Loan Application Denial',
    initiated_by: 'CARMAX 7810-LAX',
    details: {
      application_number: 'XXXX6243',
      condition: 'Denial',
    },
    reasons: [
      'Delinquent credit obligations',
      'Excessive obligations in relation to income',
      'Length of employment',
    ],
    credit_report_agency: 'Experian',
    credit_report_agency_details: 'PO Box 2002, Allen, TX 75013, 888-397-3742, www.experian.com',
    credit_score: 628,
    credit_score_date: '2024-02-19',
    credit_score_range: '300-850 (FICO)',
    credit_score_factors: [
      'Serious delinquency',
      'High balance/limit ratio',
      'Time since delinquency recent/unknown',
      'Length of account history',
      'Too many inquiries',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carmax purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial and reasons cited.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 23,
    document_source: 'Capital One Auto Finance (Letter - Auto Loan Denial)',
    sender_name: 'Capital One Auto Finance',
    sender_address: 'PO Box 259407, Plano, TX 75025',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456-2, Los Angeles, CA 90045',
    date: '2024-03-03',
    action_type: 'Auto Loan Application Denial',
    initiated_by: 'CARMAX 7810-LAX',
    details: {
      application_number: 'XXXX6243',
      condition: 'Denial',
    },
    reasons: [
      'Delinquent credit obligations',
      'Excessive obligations in relation to income',
      'Length of employment',
    ],
    credit_report_agency: 'Experian',
    credit_report_agency_details: 'PO Box 2002, Allen, TX 75013, 888-397-3742, www.experian.com',
    credit_score: 628,
    credit_score_date: '2024-02-19',
    credit_score_range: '300-850 (FICO)',
    credit_score_factors: [
      'Serious delinquency',
      'High balance/limit ratio',
      'Time since delinquency recent/unknown',
      'Length of account history',
      'Too many inquiries',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carmax purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial and reasons cited.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 24,
    document_source: 'Ally Bank (Letter - Auto Loan Denial)',
    sender_name: 'Ally Bank',
    sender_address: 'PO Box 380901, Bloomington, MN 55438',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456-2, Los Angeles, CA 90045',
    date: '2024-03-03',
    action_type: 'Auto Loan Application Denial',
    initiated_by: 'CARMAX 7810-LAX',
    details: {
      application_number: 'XXXX6243',
      condition: 'Denial',
    },
    reasons: [
      'Delinquent credit obligations',
      'Excessive obligations in relation to income',
      'Length of employment',
    ],
    credit_report_agency: 'Experian',
    credit_report_agency_details: 'PO Box 2002, Allen, TX 75013, 888-397-3742, www.experian.com',
    credit_score: 628,
    credit_score_date: '2024-02-19',
    credit_score_range: '300-850 (FICO)',
    credit_score_factors: [
      'Serious delinquency',
      'High balance/limit ratio',
      'Time since delinquency recent/unknown',
      'Length of account history',
      'Too many inquiries',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carmax purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial and reasons cited.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 25,
    document_source: 'Chase Auto (Letter - Auto Loan Denial)',
    sender_name: 'JPMorgan Chase Bank, N.A.',
    sender_address: 'PO Box 901076, Fort Worth, TX 76101-2076',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456-2, Los Angeles, CA 90045',
    date: '2024-03-03',
    action_type: 'Auto Loan Application Denial',
    initiated_by: 'CARMAX 7810-LAX',
    details: {
      application_number: 'XXXX6243',
      condition: 'Denial',
    },
    reasons: [
      'Delinquent credit obligations',
      'Excessive obligations in relation to income',
      'Length of employment',
    ],
    credit_report_agency: 'Experian',
    credit_report_agency_details: 'PO Box 2002, Allen, TX 75013, 888-397-3742, www.experian.com',
    credit_score: 628,
    credit_score_date: '2024-02-19',
    credit_score_range: '300-850 (FICO)',
    credit_score_factors: [
      'Serious delinquency',
      'High balance/limit ratio',
      'Time since delinquency recent/unknown',
      'Length of account history',
      'Too many inquiries',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carmax purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial and reasons cited.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 26,
    document_source: 'Essex Property Trust (Implied) (Letter - Rental Application Decision)',
    sender_name: 'Essex Property Trust (Implied)',
    sender_address: null,
    recipient_name: 'Nyree Hinton',
    recipient_address: 'Related to 616 Masselin Avenue, 210 application',
    date: '2024-06-04',
    action_type: 'Conditional Rental Application Approval',
    details: {
      property: 'Tiffany Court',
      condition: 'Requires additional security deposit of $2,187',
    },
    reasons: [
      'High balances',
      'Too many inquiries',
      'High revolving balances',
      'Recent auto delinquency too short',
    ],
    credit_report_agency:
      'TransUnion Consumer Solutions; TransUnion Rental Screening Solutions; etc.',
    credit_report_agency_details:
      'TransUnion Consumer Solutions: PO Box 2000 Chester, PA 19022-2000 1-800-916-8800',
    credit_score: 605,
    credit_score_date: '2024-06-05',
    credit_score_range: '350-850',
    credit_score_factors: [
      'High balances',
      'Too many inquiries',
      'High revolving balances',
      'Recent auto delinquency too short',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-PAY',
        status: 'Applicable - $2,187 Amount Stated',
        notes: 'Direct cost imposed by adverse action.',
        evidence_needed_ref: ['PEC-PAY-01 (Proof of Payment)'],
      },
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable rental application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute reasons.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration/humiliation of needing higher deposit.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 27,
    document_source: 'Unknown Credit Monitoring Service (Image - Score Update)',
    sender_name: 'Unknown',
    sender_address: null,
    recipient_name: 'Nyree Hinton',
    recipient_address: null,
    date: '2024-01-19',
    action_type: 'Credit Score Update / Change Alert',
    details: 'Score dropped 75 points since 2023-10-05.',
    credit_report_agency: 'TransUnion',
    credit_report_agency_details: null,
    credit_score: 583,
    credit_score_date: '2024-01-19',
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify monitoring cost IF service purchased *because* of discovered issues.',
        evidence_needed_ref: ['PEC-OOP-02'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Significant score drop is inherently stressful.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Directly documents damage to creditworthiness metric.',
        evidence_needed_ref: ['NONPEC-REP-03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 28,
    document_source: 'Capital One Auto Finance (Letter - Auto Financing Denial)',
    sender_name: 'Capital One Auto Finance',
    sender_address: '7933 Preston Road, Plano, TX 75024',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456-2, Los Angeles, CA 90045',
    date: '2024-03-06',
    action_type: 'Auto Financing Request Denial',
    details: {
      reference: '266820386',
    },
    reasons: ['Too many delinquent past or present Capital One installment credit obligation(s)'],
    credit_report_agency: 'Not Mentioned (Assumed Internal)',
    credit_report_agency_details: null,
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes:
          'Stress/frustration from denial based on internal history potentially linked to original dispute.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 29,
    document_source: 'Bank of America (Letter - Credit Limit Change)',
    sender_name: 'Bank of America',
    sender_address: 'PO Box 660441, Dallas, TX 75266-0441',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 CHURCH RD, EASTON PA 18045-2971',
    date: '2024-01-03',
    action_type: 'Credit Limit Reduction',
    details: {
      account_ending_in: '4041',
      new_total_credit_line: '1900.00',
    },
    reasons: [
      'Limited/no deposit/investment balances',
      'Number revolving accounts w balances',
      'Current/past delinquency/derog/collection',
      'Current/past delinquency w us',
    ],
    credit_report_agency: 'TransUnion',
    credit_report_agency_details: 'PO Box 1000, Chester, PA 19016-1000, 1.800.888.4213',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction and delinquency reasons.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 30,
    document_source: 'PA Forward Student Loans (Email - Loan Decision)',
    sender_name: 'PA Forward Student Loans (by Pheaa)',
    sender_address: 'no_reply@apply.pheaa.org',
    recipient_name: 'Nyree',
    recipient_email: 'NYREEHINTON@GMAIL.COM',
    date: '2024-02-08',
    application_date: '2024-01-19',
    action_type: 'Student Loan Application Denial (as single applicant)',
    details: {
      application_id: '6105954',
      condition: 'Offer to add qualified co-signer by 2024-03-04',
    },
    reasons: ['Credit Score does not meet minimum requirements'],
    credit_report_agency: 'Not Specified (Implied)',
    credit_report_agency_details: null,
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost funding obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Direct link to quantifying Harvard withdrawal impact.',
        evidence_needed_ref: ['PEC-OPP-01', 'PEC-OPP-02 (Harvard)'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial impacting education.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 31,
    document_source: 'Apple Card/Goldman Sachs (Email - Credit Limit Change)',
    sender_name: 'Apple Card Support / Goldman Sachs Bank USA',
    sender_address: undefined,
    recipient_name: 'Nyree Hinton',
    recipient_email: 'nyreehinton@gmail.com',
    date: '2024-01-16',
    action_type: 'Credit Limit Reduction',
    details: {
      new_credit_limit: '2200.00',
    },
    reasons: ['TransUnion report shows recently reported past due on one or more account(s).'],
    credit_report_agency: 'TransUnion Consumer Solutions',
    credit_report_agency_details: null,
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction based on past due reason.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 32,
    document_source: 'American Credit Acceptance (Letter - Auto Loan Denial/Modified Offer)',
    sender_name: 'American Credit Acceptance, LLC',
    sender_address: '961 E. Main St. 2nd Floor, Spartanburg, SC 29302',
    recipient_name: 'Nyree Hinton',
    recipient_address: '5901 Center Dr, Apt 456-2, Los Angeles, CA 90045',
    date: '2024-03-03',
    action_type: 'Auto Loan Application Denial (as submitted); Modified terms offered',
    initiated_by: 'CARMAX 7810-LAX',
    details: {
      application_number: 'XXXX6243',
      condition: 'Modified offer via dealer',
    },
    reasons: ['Not specified, requires contact'],
    credit_report_agency: 'TransUnion',
    credit_report_agency_details: '2 Baldwin Place, Chester, PA 19022 (800) 888-4213',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: "Quantify IF modified terms accepted AND worse than 'but-for'.",
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Carmax purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial/modified offer.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 33,
    document_source: 'Citi (Letter - Credit Limit Lowered)',
    sender_name: 'Citi',
    sender_address: 'PO Box 6494, Sioux Falls, SD 57117-6494',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 CHURCH RD, EASTON PA 18045-2971',
    date: '2024-02-05',
    action_type: 'Credit Limit Reduction',
    details: {
      account: 'Citi® Double Cash Mastercard®',
      account_ending_in: '1752',
      new_credit_limit: '1510',
      cash_advance_limit: '0',
    },
    reasons: [
      'Score too low',
      'High revolving balances relative to limits',
      'Account(s) past due in last 12 months',
    ],
    credit_report_agency: 'Equifax Credit Information Services',
    credit_report_agency_details:
      'PO Box 740241, Atlanta, GA 30374-0241, 1-800-685-1111, www.equifax.com',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: [
      'Balances on revolving accounts too high relative to limits',
      'Account(s) past due in last 12 months',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if reduction forced reliance on higher-cost credit.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute limit reduction reason.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from limit reduction and past due reasons.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 34,
    document_source: 'Bank of Lake Mills / MPOWER Financing (Letter - Student Loan Denial)',
    sender_name: 'Bank of Lake Mills / MPOWER Financing',
    sender_address: '1101 Connecticut Ave NW Suite 900, Washington, DC 20036',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 Church Road, Easton, Pennsylvania, 18045',
    date: '2024-01-24',
    action_type: 'Fixed-rate student loan application denial',
    details: {
      loan_type: 'Fixed-rate student loan',
    },
    reasons: ['Delinquent past or present credit obligations'],
    credit_report_agency: 'TransUnion',
    credit_report_agency_details:
      'P.O.Box 1000, Chester, PA 19016, United States, Tel: 800-888-4213',
    credit_score: null,
    credit_score_date: null,
    credit_score_range: null,
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost funding obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Direct link to quantifying Harvard withdrawal impact.',
        evidence_needed_ref: ['PEC-OPP-01', 'PEC-OPP-02 (Harvard)'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial impacting education, reason cited.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 35,
    document_source: 'Bank of America (Notice - Credit Score Disclosure)',
    sender_name: 'Bank of America',
    sender_address: undefined,
    recipient_name: 'Nyree Hinton',
    recipient_address: undefined,
    date: undefined,
    action_type: 'Credit Score Disclosure',
    details: 'Associated with Doc 1 (Limit reduction 2024-03-07)',
    credit_report_agency: 'TransUnion',
    credit_report_agency_details:
      'PO Box 1000, Chester, PA 19016-1000, 800.888.4213, www.transunion.com/myoptions',
    credit_score: 628,
    credit_score_date: '2024-02-19',
    credit_score_range: '300-850 (FICO)',
    credit_score_factors: [
      'Serious delinquency',
      'High balance/limit ratio',
      'Time since delinquency recent/unknown',
      'Length of account history',
      'Too many inquiries',
    ],
    applicable_pecuniary_damages: [],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Documents low score and negative factors contributing to overall stress.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Documents negative factors harming reputation.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 36,
    document_source: 'Westlake Financial (Letter - Adverse Action Notice)',
    sender_name: 'Westlake Financial',
    sender_address: 'P.O. Box 76809, Los Angeles, CA 90076-0809',
    recipient_name: 'Nyree Hinton',
    recipient_address: '4254 CHURCH RD, EASTON, PA 18045',
    date: '2024-04-22',
    action_type: 'Adverse Action Notice - Credit Denied',
    details: {
      reference_id: '90600588',
      purchase_from_vehicle: 'ST.CHARLES MOTORCARS',
    },
    reasons: ['Frozen credit file'],
    credit_report_agency: 'Not specified primary; NOWCOM listed for contact',
    credit_report_agency_details: 'NOWCOM CORPORATION, DEALERCENTER COMPLIANCE DEPARTMENT',
    credit_score: 0,
    credit_score_date: '2024-03-26',
    credit_score_range: '0-0',
    credit_score_factors: null,
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee was paid.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if St. Charles purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute reason given (frozen file).',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Contributes to negative credit profile perception.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
  createAdverseAction({
    document_index: 37,
    document_source: 'US Bank (Letter - Auto Loan Denial)',
    sender_name: 'U.S. Bank N.A.',
    sender_address: 'CN-OH-W7CD, 425 Walnut Street 7th Floor, CINCINNATI OH 45202',
    recipient_name: 'Nyree Hinton',
    recipient_address: '616 Masselin Ave Apt 210, Los Angeles CA. 90036-3732',
    date: '2024-09-30',
    application_date: '2024-09-16',
    action_type: 'Auto Loan Application Denial',
    initiated_by: 'VOLVO PALO ALTO',
    details: {
      application_number: '39687638',
    },
    reasons: [
      'Credit Does Not Support LTV',
      'Terms requested not offered',
      'Excessive Balances relative to Limit',
      'Excessive Inquiries',
    ],
    credit_report_agency: 'Experian',
    credit_report_agency_details: 'P.O Box 2002, Allen, TX 750132002, (888) 397-3742',
    credit_score: 643,
    credit_score_date: '2024-09-16',
    credit_score_range: '250-900',
    credit_score_factors: [
      'High Ratio Balances/Limits',
      'Short Account History',
      'High Amount Owed',
      'High Loan Balance/Amount Ratio',
      'Too Many Inquiries',
    ],
    applicable_pecuniary_damages: [
      {
        id: 'PEC-FEE',
        status: 'Applicable - Quantification TBD',
        notes: 'Verify if non-refundable application fee paid to Volvo PA.',
        evidence_needed_ref: ['PEC-FEE-01', 'PEC-FEE-02'],
      },
      {
        id: 'PEC-COST',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if alternative, higher-cost financing obtained.',
        evidence_needed_ref: ['PEC-COST-01', 'PEC-COST-03', 'PEC-COST-04'],
      },
      {
        id: 'PEC-DEP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify if Volvo purchase failed & deposit lost.',
        evidence_needed_ref: ['PEC-DEP-01', 'PEC-DEP-02', 'PEC-DEP-03'],
      },
      {
        id: 'PEC-OPP',
        status: 'Applicable - Quantification TBD',
        notes: 'Quantify cost of inability to replace defective vehicle.',
        evidence_needed_ref: ['Repair Bills', 'Alt. Transport Costs', 'Replacement Vehicle Docs'],
      },
      {
        id: 'PEC-OOP',
        status: 'Applicable - Quantification TBD',
        notes: 'Costs to investigate/dispute denial.',
        evidence_needed_ref: ['PEC-OOP-01 to 06'],
      },
    ],
    applicable_non_pecuniary_damages: [
      {
        id: 'NONPEC-ED',
        status: 'Applicable',
        notes: 'Stress/frustration from denial.',
        evidence_needed_ref: ['NONPEC-ED-01 to 05'],
      },
      {
        id: 'NONPEC-REP',
        status: 'Applicable',
        notes: 'Negative factors cited damage reputation.',
        evidence_needed_ref: ['NONPEC-REP-01 to 03'],
      },
    ],
  }),
];
