import { CreditReport } from '../../shared/schema';

// Credit report data based on documents in attached_assets/documents/credit-reports
export const creditReportsData: CreditReport[] = [
  // Baseline Reports
  {
    report_need_id: 'BASELINE-01',
    cra: 'Experian',
    date_range: 'June/July 2023',
    reason_needed: 'Establish baseline creditworthiness before alleged inaccurate reporting began.',
    linked_docs: [-1],
    status: 'Satisfied',
    date_requested: '2023-06-11',
    date_received: '2023-07-06',
    notes: 'Have complete baseline series: June 11, June 28, and July 6, 2023',
  },
  {
    report_need_id: 'BASELINE-02',
    cra: 'TransUnion',
    date_range: 'June/July 2023',
    reason_needed: 'Establish baseline creditworthiness before alleged inaccurate reporting began.',
    linked_docs: [-1],
    status: 'Outstanding',
    notes: 'Need historical reports from this period',
  },
  {
    report_need_id: 'BASELINE-03',
    cra: 'Equifax',
    date_range: 'June/July 2023',
    reason_needed: 'Establish baseline creditworthiness before alleged inaccurate reporting began.',
    linked_docs: [-1],
    status: 'Outstanding',
    notes: 'Need historical reports from this period',
  },

  // Current Status Reports
  {
    report_need_id: 'CURRENT-01',
    cra: 'Experian',
    date_range: 'Most Recent Available',
    reason_needed: 'Show current status of reporting and whether errors persist.',
    linked_docs: [-1],
    status: 'Satisfied',
    date_requested: '2024-02-12',
    date_received: '2024-02-12',
    notes: 'Most recent report from Feb 12, 2024',
  },
  {
    report_need_id: 'CURRENT-02',
    cra: 'TransUnion',
    date_range: 'Most Recent Available',
    reason_needed: 'Show current status of reporting and whether errors persist.',
    linked_docs: [-1],
    status: 'Satisfied',
    date_requested: '2024-06-04',
    date_received: '2024-06-04',
    notes: 'Most recent report from June 4, 2024',
  },
  {
    report_need_id: 'CURRENT-03',
    cra: 'Equifax',
    date_range: 'Most Recent Available',
    reason_needed: 'Show current status of reporting and whether errors persist.',
    linked_docs: [-1],
    status: 'Satisfied',
    date_requested: '2024-04-06',
    date_received: '2024-04-06',
    notes: 'Most recent report from April 6, 2024',
  },

  // Satisfied Damage Requirements
  {
    report_need_id: 'PREQ-01-Chase-0757-Exp',
    cra: 'Experian',
    date_range: 'January 2024',
    reason_needed: 'Required for PEC-COST-03: Chase 0757 limit reduction (Doc 3)',
    linked_docs: [3],
    status: 'Satisfied',
    date_requested: '2024-01-02',
    date_received: '2024-01-08',
    notes: 'Have Jan 2 and Jan 8 reports, matching timing of reduction (Jan 18)',
  },
  {
    report_need_id: 'PREQ-01-Chase-7293-Exp',
    cra: 'Experian',
    date_range: 'January 2024',
    reason_needed: 'Required for PEC-COST-04: Chase Amazon 7293 limit reduction (Doc 4)',
    linked_docs: [4],
    status: 'Satisfied',
    date_requested: '2024-01-02',
    date_received: '2024-01-08',
    notes: 'Have Jan 2 and Jan 8 reports, matching timing of reduction (Jan 18)',
  },
  {
    report_need_id: 'PREQ-01-Amex-095008-Exp',
    cra: 'Experian',
    date_range: 'January 2024',
    reason_needed: 'Required for PEC-COST-08: Amex preset limit (Doc 25)',
    linked_docs: [25],
    status: 'Satisfied',
    date_requested: '2024-01-02',
    date_received: '2024-01-08',
    notes: 'Have Jan 2 and Jan 8 reports, matching timing of limit set (Jan 23)',
  },
  {
    report_need_id: 'PREQ-01-Essex-TU',
    cra: 'TransUnion',
    date_range: 'June 2024',
    reason_needed: 'Required for PEC-PAY-01: Essex security deposit (Doc 10)',
    linked_docs: [10],
    status: 'Satisfied',
    date_requested: '2024-06-04',
    date_received: '2024-06-05',
    notes: 'Have June 5 report, exactly matching adverse action date',
  },

  // Outstanding Immediate Requirements
  {
    report_need_id: 'PREQ-01-BofA-1775-TU',
    cra: 'TransUnion',
    date_range: 'March 2024',
    reason_needed: 'Required for PEC-COST-02: BofA 1775 limit reduction (Doc 1)',
    linked_docs: [1],
    status: 'Outstanding',
    notes: 'Need report from around March 7, 2024',
  },
  {
    report_need_id: 'PREQ-01-BofA-4041-TU',
    cra: 'TransUnion',
    date_range: 'January 2024',
    reason_needed: 'Required for PEC-COST-05: BofA 4041 limit reduction (Doc 14)',
    linked_docs: [14],
    status: 'Outstanding',
    notes: 'Need report from around Jan 3, 2024',
  },
  {
    report_need_id: 'PREQ-01-AppleCard-TU',
    cra: 'TransUnion',
    date_range: 'January 2024',
    reason_needed: 'Required for PEC-COST-06: Apple Card limit reduction (Doc 16)',
    linked_docs: [16],
    status: 'Outstanding',
    notes: 'Need report from around Jan 16, 2024',
  },
  {
    report_need_id: 'PREQ-01-Citi-1752-EQ',
    cra: 'Equifax',
    date_range: 'February 2024',
    reason_needed: 'Required for PEC-COST-07: Citi Double Cash limit reduction (Doc 18)',
    linked_docs: [18],
    status: 'Outstanding',
    notes: 'Need report from around Feb 5, 2024',
  },

  // Future Requirements (Not Yet Due)
  {
    report_need_id: 'PREQ-01-Golden1-Exp',
    cra: 'Experian',
    date_range: 'September 2024',
    reason_needed: 'Required for PEC-COST-01: Golden1 unfavorable terms (Doc 26)',
    linked_docs: [26],
    status: 'Outstanding',
    notes: 'Will need report from around Sept 17, 2024 when available',
  },
  {
    report_need_id: 'PREQ-01-SmartBiz-Exp',
    cra: 'Experian',
    date_range: 'August 2024',
    reason_needed: 'Required for PEC-OPP-03: SmartBiz business loan denial (Doc 31)',
    linked_docs: [31],
    status: 'Outstanding',
    notes: 'Will need report from around Aug 8, 2024 when available',
  },

  // Experian Reports for Specific Needs
  {
    report_need_id: 'CR-NEED-02',
    cra: 'Experian',
    date_range: 'January 2024',
    reason_needed:
      'Basis for adverse action by creditor (Chase Cards Doc 3/4, Chase Auto Doc 8, Earnest Doc 21, AmEx Doc 25, OneMain Doc 33).',
    linked_docs: [3, 4, 8, 21, 25, 33],
    status: 'Satisfied',
    date_requested: '2024-01-02',
    date_received: '2024-01-08',
    notes: 'Have both Jan 2 and Jan 8, 2024 reports with detailed credit data',
  },
  {
    report_need_id: 'CR-NEED-03',
    cra: 'Experian',
    date_range: 'February 2024',
    reason_needed: 'Basis for adverse action by creditor (Ally Doc 5).',
    linked_docs: [5],
    status: 'Satisfied',
    date_requested: '2024-02-08',
    date_received: '2024-02-12',
    notes: 'Have both Feb 8 and Feb 12, 2024 reports',
  },
  {
    report_need_id: 'CR-NEED-06',
    cra: 'Experian',
    date_range: 'March 2024',
    reason_needed:
      'Basis for adverse action by creditor (Ally Doc 6, Exeter Doc 22, Global Doc 24, Chase Auto Doc 34, Westlake Doc 37, OneMain Doc 27).',
    linked_docs: [6, 22, 24, 34, 37, 27],
    status: 'Satisfied',
    date_requested: '2024-02-08',
    date_received: '2024-02-12',
    notes: 'Feb 8 and Feb 12 reports provide context for March actions',
  },

  // TransUnion Reports for Specific Needs
  {
    report_need_id: 'CR-NEED-11',
    cra: 'TransUnion',
    date_range: 'June 2024',
    reason_needed: 'Basis for adverse action by creditor (Essex Doc 10).',
    linked_docs: [10],
    status: 'Satisfied',
    date_requested: '2024-06-04',
    date_received: '2024-06-05',
    notes: 'June 5, 2024 report matches adverse action date',
  },

  // Outstanding Reports (keeping track of what we still need)
  {
    report_need_id: 'CR-NEED-04',
    cra: 'SageStream',
    date_range: 'February 2024',
    reason_needed: 'Basis for adverse action by creditor (Ally Doc 5).',
    linked_docs: [5],
    status: 'Outstanding',
    notes: 'Need to obtain SageStream report',
  },
  {
    report_need_id: 'CR-NEED-07',
    cra: 'SageStream',
    date_range: 'March 2024',
    reason_needed:
      'Basis for adverse action by creditor (Ally Doc 6, Global Doc 24, Westlake Doc 37).',
    linked_docs: [6, 24, 37],
    status: 'Outstanding',
    notes: 'Need to obtain SageStream report',
  },
  {
    report_need_id: 'CR-NEED-18',
    cra: 'NCTUE',
    date_range: 'March 2024',
    reason_needed: 'Listed as source by creditor (Global Doc 24).',
    linked_docs: [24],
    status: 'Outstanding',
    notes: 'Need to obtain NCTUE report',
  },
  {
    report_need_id: 'CR-NEED-27',
    cra: 'NOWCOM',
    date_range: 'March/April 2024',
    reason_needed: 'Listed as source by creditor (Westlake Doc 37).',
    linked_docs: [37],
    status: 'Outstanding',
    notes: 'May require discovery from Westlake/NOWCOM',
  },
];
