[build]
  command = "npm run build"
  publish = "dist"
  base = "/"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
  framework = "#custom"